apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
# - my-pv.yaml
# - my-pvc.yaml
- my-dynamic-pv.yaml
- ../../base

# commonLabels:
#   someLabelName: someLabelValueDev
#   myEnv: my-dev-label

namespace: wildfly-dev

configMapGenerator:
- name: myconfigmap
  behavior: merge
  literals:
  - MY_ENV_VARIABLE=MY_DEV_VALUE

patches:
- path: my-wildfly-deployment.yaml
# - path: my-pvc.yaml
# patch to update port numbers for services on local machine
- target:
      kind: Service
      name: wildfly-service
  patch: |
    - op: replace
      path: /spec/ports/0/port
      value: 8080
- target:
      kind: Ingress
      name: my-ingress-tls
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: myservicea.dev
    - op: replace
      path: /spec/tls/0/hosts/1
      value: myserviceb.dev
    - op: replace
      path: /spec/rules/0/host
      value: myservicea.dev
    - op: replace
      path: /spec/rules/1/host
      value: myserviceb.dev
# - target:
#     kind: PersistentVolume
#     name: my-host-pv-base
#   patch: |-
#     - op: delete