apiVersion: v1
kind: Secret
metadata:
  name: my-appsets-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/yusufbata/docker-wildfly-argocd.git
  # password: my-password
  # username: my-username
  insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"