apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../base

# commonLabels:
#   someLabelName: someLabelValueDev
#   myEnv: my-dev-label

namespace: wildfly-dev