apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
# - my-pv.yaml
# - my-pvc.yaml
# - my-dynamic-pv.yaml
- my-dynamic-pvc.yaml
- my-configmap.yaml
- my-wildfly-deployment.yaml
#  Deploy an NGINX Ingress controller
# - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
- my-ingress-tls.yaml

configMapGenerator:
- name: my-env-configmap
  files:
    - env-config/.env.server
    - env-config/datasource-local.properties
# - name: my-datasource-configmap
#   files:
#     - env-config/datasource-local.properties