# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: my-host-pv
# spec:
#   capacity: 
#     storage: 20Mi
#   volumeMode: Filesystem
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /Users/F3657051/dev/docker/docker-wildfly/docker/env-config
#     type: Directory
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-dynamic-host-pvc
spec:
  # storageClassName: my-storage-class
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

  # volumeName: my-host-pv-base
  # accessModes:
  #   - ReadWriteOnce
  # storageClassName: standard
  # resources:
  #   requests: 
  #     storage: 10Mi