apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - namespace.yaml
# - my-pv.yaml
- ../../base

commonLabels:
  someLabelName: someLabelValueDigitalOcean
  myEnv: my-do-label

# namespace: my-do-namespace

configMapGenerator:
- name: myconfigmap
  behavior: merge
  literals:
  - MY_ENV_VARIABLE=MY_DIGITAL_OCEAN_VALUE

patches:
- path: my-wildfly-deployment.yaml
- path: my-dynamic-pvc.yaml
# - path: my-pvc.yaml
# patch to update port numbers for services on local machine
# - target:
#       kind: Service
#       name: wildfly-service
#   patch: |
#     - op: replace
#       path: /spec/ports/0/port
#       value: 8080