apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-dynamic-host-pvc
spec:
  storageClassName: do-block-storage
  # storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi