apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- my-pv.yaml
- ../../base

commonLabels:
  someLabelName: someLabelValueProd
  myEnv: my-prod-label

namespace: my-prod-namespace

configMapGenerator:
- name: myconfigmap
  behavior: merge
  literals:
  - MY_ENV_VARIABLE=MY_PROD_VALUE

# patchesStrategicMerge:
# - |-
#   apiVersion: v1
#   kind: PersistentVolume
#   metadata:
#     name: my-host-pv-base
#   $patch: delete

patches:
- path: my-wildfly-deployment.yaml
# - path: delete-my-pv-base.yaml
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: my-host-pv-base
# - patch: |-
#     $patch: delete
#     apiVersion: v1
#     kind: PersistentVolume
#     metadata:
#       name: my-dynamic-pv-local-base
- target:
      kind: PersistentVolume
      name: my-dynamic-pv-local-base
  patch: |
    - op: replace
      path: /metadata/name
      value: my-dynamic-pv-local-prod
- patch: |-
    $patch: delete
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: my-storage-class
- path: my-pvc.yaml
# patch to update port numbers for services on local machine
- target:
      kind: Service
      name: wildfly-service
  patch: |
    - op: replace
      path: /spec/ports/0/port
      value: 8082