apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-dynamic-pv-local-base
spec:
  storageClassName: my-storage-class
  # default storage class is hostpath
  # storageClassName: hostpath
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/F3657051/dev/docker/docker-wildfly/static-content
    type: Directory
  persistentVolumeReclaimPolicy: Retain
---
# apiVersion: v1
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: my-storage-class
# provisioner: docker.io/hostpath

  # capacity: 
  #   storage: 100Mi
  # volumeMode: Filesystem
  # storageClassName: standard
  # accessModes:
  #   - ReadWriteMany
  # hostPath:
  #   path: /Users/F3657051/dev/docker/docker-wildfly/docker/env-config
  #   type: Directory
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: my-host-pvc
# spec:
#   volumeName: my-host-pv
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     requests: 
#       storage: 10Mi