apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-cluster-common
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yusufbata/docker-wildfly-argocd.git
    targetRevision: HEAD
    path: clusters/dev/helm
    # helm:
    #   valueFiles:
    #   - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true